services:
  - type: web
    name: teaser-island-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/online-players
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 